# nixpacks.toml

[phases.setup]
# Installs packages using Nix
# Use nixPkgs instead of aptPkgs for potentially better reliability on Railway
nixPkgs = ["vips", "libheif", "pkg-config"]

[start]
# Make sure this matches your actual start command in package.json or Procfile
cmd = "npm start" 