# nixpacks.toml

[phases.setup]
# Installs packages using Nix
# Use nixPkgs instead of aptPkgs for potentially better reliability on Railway
# Using 'vips' instead of 'libvips' as the Nix package name
# ADDED nodejs_20 explicitly to ensure Node/npm are available
nixPkgs = ["vips", "libheif", "pkg-config", "nodejs_20"]

[start]
# Make sure this matches your actual start command in package.json or Procfile
cmd = "node railway-start.js"