[phases.setup]
nixPkgs = ["nodejs-18_x", "gcc", "libvips"]

[variables]
NODE_ENV = "production"
NODE_VERSION = "18.18.0"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_FETCH_TIMEOUT = "300000"
NPM_CONFIG_FETCH_RETRIES = "5"
