[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-optional --no-package-lock"

[deploy]
startCommand = "node minimal-server.js"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
