[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-optional --no-package-lock"
watchPatterns = ["package.json", "package-lock.json"]

[nixpacks]
install_cmd = "npm install --no-optional --no-package-lock"
start_cmd = "node server.js"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
