[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-optional"

[deploy]
startCommand = "node core-server.js"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
