[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node railway-start.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
