[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
