-- Ensure all micronutrient columns exist in the ingredients table
-- This migration adds any missing micronutrient columns

-- Carbohydrates
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS fiber NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS starch NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS sugars NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS added_sugars NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS net_carbs NUMERIC(10, 2);

-- Lipids
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS saturated NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS monounsaturated NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS polyunsaturated NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS omega3 NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS omega6 NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS trans NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS cholesterol NUMERIC(10, 2);

-- Protein/Amino Acids
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS histidine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS isoleucine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS leucine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS lysine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS methionine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS phenylalanine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS threonine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS tryptophan NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS tyrosine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS valine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS cystine NUMERIC(10, 2);

-- Vitamins
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_a NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS thiamine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS riboflavin NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS niacin NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS pantothenic_acid NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_b6 NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_b12 NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS folate NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_c NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_d NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_e NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS vitamin_k NUMERIC(10, 2);

-- Minerals
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS calcium NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS copper NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS iron NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS magnesium NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS manganese NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS phosphorus NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS potassium NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS selenium NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS sodium NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS zinc NUMERIC(10, 2);

-- General
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS alcohol NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS caffeine NUMERIC(10, 2);
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS water NUMERIC(10, 2);
